### ISSUE TITLE
Rename plugin to apt-maven-plugin

### ISSUE THREAD

**Issue by grossws** [dernasherbrezon/apt-maven-plugin#1]
`maven-<something>-plugin` is reserved for official Apache Maven plugins and is highly discouraged. Take a look at https://maven.apache.org/guides/plugin/guide-java-plugin-development.html

**Comment by dernasherbrezon** [comment]
Fixed

**Comment by grossws** [comment]
:+1:
I can also recommend to deploy it to maven central via [Sonatype OSSRH](http://central.sonatype.org/pages/ossrh-guide.html).

**Comment by dernasherbrezon** [comment]
Done. See [maven central](http://search.maven.org/#artifactdetails%7Ccom.aerse.maven%7Capt-maven-plugin%7C1.5%7Cmaven-plugin)
